---
substitutions:
  homedicator_core_version_tag: "v0.3.2"

sensor:
  - !include core/config/common/sensors/wifi_signal.yaml
  - !include core/config/common/sensors/wifi_signal_percent.yaml

text_sensor:
  - !include core/config/common/text_sensors/github_release_tag.yaml
  - !include core/config/common/text_sensors/esphome_version.yaml

binary_sensor:
  - !include core/config/common/binary_sensors/indicator_button.yaml

switch:
  - !include core/config/common/switches/use_24h_clock_switch.yaml

lvgl:
  disp_bg_color: 0x1b1b1b
  gradients: !include core/config/common/lvgl/gradients.yaml
  on_idle: !include core/config/common/lvgl/on_idle.yaml
  top_layer: !include user_interface/pages/top_layer/top_layer.yaml
  theme: !include user_interface/theme/theme.yaml
  style_definitions: !include user_interface/theme/style_definitions.yaml
  pages:
    - !include user_interface/pages/settings.yaml
    - !include user_interface/pages/about.yaml


<<: !include core/config/common/fonts.yaml
<<: !include core/config/common/esphome.yaml
<<: !include core/config/common/scripts.yaml
<<: !include core/config/common/light.yaml
<<: !include core/config/common/time.yaml
<<: !include core/config/common/select.yaml
<<: !include core/config/common/globals.yaml
<<: !include core/config/common/http_request.yaml
<<: !include core/config/common/interval.yaml
