id: settings
bg_color: 0x0d0d0d
bg_opa: COVER
widgets:
  # PAGE TITLE
  - !include
      file: ../templates/page_title.yaml
      vars:
        title: "Settings"
  - obj:
      styles: content_container
      layout:
        type: FLEX
        flex_flow: ROW_WRAP
        flex_align_main: LV_FLEX_ALIGN_START
        flex_align_cross: CENTER
      widgets:
        - obj:
            width: 443
            height: 130
            radius: 15
            bg_color: 0x202020
            bg_opa: COVER
            pad_all: 0
            layout:
              type: FLEX
              flex_flow: COLUMN
              flex_align_main: SPACE_EVENLY
              flex_align_cross: LV_FLEX_ALIGN_START
              flex_align_track: LV_FLEX_ALIGN_START
              pad_row: 0
            widgets:
              - label:
                  pad_left: 30
                  text_color: 0xffffff
                  text_font: libreFranklin18
                  text: "Display brightness"
              - obj:
                  bg_opa: TRANSP
                  width: 440
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_top: 5
                  pad_bottom: 15
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_EVENLY
                    flex_align_cross: CENTER
                    flex_align_track: CENTER
                    pad_row: 0
                  widgets:
                    - label:
                        text_color: 0xffffff
                        text_font: brightness_small
                        text: "\U000F05A8"
                    - slider:
                        height: 25
                        id: lvgl_indicator_lcd_brightness_slider
                        value: 100
                        min_value: 5
                        max_value: 100
                        bg_color: 0x525a46
                        indicator:
                          bg_color: 0x92ae67
                        knob:
                          bg_color: 0xFFFFFF
                        on_press:
                          then:
                            - globals.set:
                                id: user_is_interacting
                                value: 'true'
                        on_release:
                          then:
                            - globals.set:
                                id: user_is_interacting
                                value: 'false'
                        on_value:
                          if:
                            condition:
                              lambda: |-
                                return id(user_is_interacting);
                            then:
                              - light.control:
                                  id: indicator_display_backlight
                                  state: on
                                  brightness: !lambda 'return x / 100.0;'
                    - label:
                        text_color: 0xffffff
                        text_font: brightness_big
                        text: "\U000F05A8"
        - obj:
            width: 443
            height: 80
            radius: 15
            bg_color: 0x202020
            bg_opa: COVER
            pad_all: 0
            pad_left: 30
            pad_right: 30
            layout:
              type: FLEX
              flex_flow: ROW
              flex_align_main: SPACE_BETWEEN
              flex_align_cross: CENTER
              flex_align_track: CENTER
            widgets:
              - label:
                  text_color: 0xffffff
                  text_font: libreFranklin18
                  text: "Turn off screen after"
              - dropdown:
                  id: lvgl_display_backlight_timeout
                  height: 40
                  width: 110
                  bg_color: 0x181818
                  text_color: 0xffffff
                  border_width: 0
                  text_font: montserrat_18 # Can't get the dropdown symbol to show in our font...
                  dir: TOP
                  dropdown_list:
                    bg_color: 0x292929
                    text_color: 0xffffff
                    text_font: libreFranklin18
                    border_width: 1
                    border_color: 0x999999
                    selected:
                      checked:
                        bg_color: 0x92ae67
                  options:
                    - "Never"
                    - "1 min"
                    - "3 min"
                    - "5 min"
                    - "15 min"
        - obj:
            width: 443
            height: 80
            radius: 15
            bg_color: 0x202020
            bg_opa: COVER
            pad_all: 0
            pad_left: 30
            pad_right: 30
            layout:
              type: FLEX
              flex_flow: ROW
              flex_align_main: SPACE_BETWEEN
              flex_align_cross: CENTER
              flex_align_track: CENTER
            widgets:
              - label:
                  text_color: 0xffffff
                  text_font: libreFranklin18
                  text: "Use 24-hour clock"
              - switch:
                  id: lvgl_24h_clock_switch
                  height: 40
                  width: 85
                  bg_color: 0xdddddd
        - obj:
            width: 443
            height: 80
            radius: 15
            bg_color: 0x202020
            bg_opa: COVER
            pad_all: 0
            pad_left: 30
            pad_right: 30
            on_click:
              then:
                - script.execute: hide_page_control_elements
                - lvgl.page.show:
                    animation: MOVE_LEFT
                    time: ${page_transition_time}
                    id: about
            layout:
              type: FLEX
              flex_flow: ROW
              flex_align_main: SPACE_BETWEEN
              flex_align_cross: CENTER
              flex_align_track: CENTER
            widgets:
              - label:
                  text_color: 0xffffff
                  text_font: libreFranklin18
                  text: "About this device"
              - label:
                  text_color: 0xffffff
                  text_font: ui_light_icons
                  text: "\U0000F142"
